### ISSUE TITLE
BigQuery Table Not Created

### ISSUE THREAD

**Issue by svenmueller** [terraform-google-modules/terraform-google-slo#35]
Hi,

We enabled the exporter to BigQuery (before we only exported to `Stackdriver`) and applied the TF resource in our GCP project. The TF apply command was successful but after looking into GCP, we noticed the the SLO export to BigQuery fails (cloud function ends in crashed state).

- `exporters.yaml`
```
pipeline:
  - class: Bigquery
    project_id: ${project_id}
    dataset_id: slo_reports
    table_name: report

  - class: Stackdriver
    project_id: ${stackdriver_host_project_id}

slo:
  - class: Pubsub
    project_id: ${project_id}
    topic_name: ${pubsub_topic_name}
```

- `slo-pipeline` cloud function logs
```
Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v1.py", line 402, in run_background_function _function_handler.invoke_user_function(event_object) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v1.py", line 222, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v1.py", line 219, in call_user_function event_context.Context(**request_or_event.context)) File "/user_code/main.py", line 25, in main compute.export(data, exporters) File "/env/local/lib/python3.7/site-packages/slo_generator/compute.py", line 97, in export ret = exporter.export(data, **config) File "/env/local/lib/python3.7/site-packages/slo_generator/exporters/bigquery.py", line 53, in export table_id = config['table_id'] KeyError: 'table_id'
```

When looking into BigQuery, we can see that the dataset with id "slo_reports" was created but it doesn't contain any table (e.g. "report" as defined in the `exporters.yaml`).

Any idea why we have this issue?

Thx,
Sven
